name: Test33

on:
  workflow_dispatch:
  merge_group:
  pull_request:

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

env:
  ELASTICSEARCH_URL: http://localhost:9200/

jobs:
  figureOutMatrix:
    if: github.repository == 'github/docs-internal' || github.repository == 'github/docs'
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.result }}
    steps:
      - uses: actions/github-script@98814c53be79b1d30f795b907e553d8679345975
        id: set-matrix
        with:
          script: |
            return [
              { name: 'content', path: 'tests/content', },
              { name: 'automated-pipelines', path: 'src/automated-pipelines/tests', },
              { name: 'events', path: 'src/events/tests', },
              { name: 'ghes-releases', path: 'src/ghes-releases/tests', },
              { name: 'graphql', path: 'src/graphql/tests', },
              { name: 'rest', path: 'src/rest/tests', },
              { name: 'webhooks', path: 'src/webhooks/tests', },
              { name: 'linting', path: 'src/content-linter/tests', },
              { name: 'meta', path: 'tests/meta', },
              { name: 'routing', path: 'tests/routing', },
              { name: 'rendering', path: 'tests/rendering', },
              { name: 'rendering-fixtures', path: 'tests/rendering-fixtures', },
              { name: 'search', path: 'src/search/tests', },
              { name: 'pageinfo', path: 'src/pageinfo/tests', },
              context.payload.repository.full_name === 'github/docs-internal' &&
                { name: 'translations', path: 'tests/translations', },
              { name: 'unit', path: 'tests/unit', },
            ].filter(Boolean)

  test:
    name: ${{ matrix.name }}
    needs: figureOutMatrix
    runs-on: ${{ fromJSON('["ubuntu-latest", "ubuntu-20.04-xl"]')[github.repository == 'github/docs-internal'] }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs.figureOutMatrix.outputs.matrix) }}
    steps:
      - name: Check out repo
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab

      - uses: ./.github/actions/setup-elasticsearch
        if: ${{ matrix.name == 'search' || matrix.name == 'translations' }}

      - uses: ./.github/actions/node-npm-setup

      - uses: ./.github/actions/get-docs-early-access
        if: ${{ github.repository == 'github/docs-internal' }}
        with:
          token: ${{ secrets.DOCUBOT_REPO_PAT }}

      - name: Check the test fixture data (if applicable)
        if: ${{ matrix.name == 'rendering-fixtures' }}
        run: ./script/copy-fixture-data.js --check
      - name: Check the test fixture content (if applicable)
        if: ${{ matrix.name == 'rendering-fixtures' }}
        env:
          ROOT: tests/fixtures
        run: |
          ./script/update-internal-links.js --dry-run --check --strict \
            tests/fixtures/content \
            --exclude tests/fixtures/content/get-started/foo/typo-autotitling.md \
            --exclude tests/fixtures/content/get-started/foo/anchor-autotitling.md
          ./script/update-internal-links.js --dry-run --check --strict \
            tests/fixtures/data

      - name: Clone all translations
        if: ${{ matrix.name == 'translations' }}
        uses: ./.github/actions/clone-translations
        with:
          token: ${{ secrets.DOCUBOT_REPO_PAT }}

      - name: Gather files changed
        if: ${{ matrix.name == 'linting' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR: ${{ github.event.pull_request.number }}
          HEAD: ${{ github.event.pull_request.head.ref || github.event.merge_group.head_ref }}
        run: |
          if [ -n "$PR" ]
          then
            echo __ running gh pr diff __
            DIFF=`gh pr diff $PR --name-only`
          elif [ -n "$HEAD" ]
          then
            echo __ running git fetch main __
            git fetch origin main --depth 1
            echo __ running git diff __
            DIFF=`git diff --name-only origin/main`
          else
            echo __ no head, empty diff __
            DIFF=''
          fi
          echo __ DIFF found __
          echo $DIFF
          echo __ format, write to get_diff_files.txt __
          echo $DIFF | tr '\n' ' ' > get_diff_files.txt

      - name: Cache nextjs build
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8
        with:
          path: .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('package*.json') }}

      - name: Run build script
        run: npm run build

      - uses: ./.github/actions/warmup-remotejson-cache
        if: ${{ matrix.name == 'routing' }}

      - name: Index fixtures into the local Elasticsearch
        if: ${{ matrix.name == 'search' || matrix.name == 'translations' }}
        run: npm run index-test-fixtures

      - name: Run tests
        env:
          DIFF_FILE: get_diff_files.txt
          CHANGELOG_CACHE_FILE_PATH: tests/fixtures/changelog-feed.json
          ENABLED_LANGUAGES: ${{ matrix.name == 'translations' && 'all' || '' }}
          ROOT: ${{ (matrix.name == 'rendering-fixtures' || matrix.name == 'pageinfo') && 'tests/fixtures' || ''}}
        run: npm test -- ${{ matrix.path }}/
