name: Deploy-Android-TEST

env:
  APP_CENTER_TOKEN: ${{ secrets.APP_CENTER_TOKEN_MYAPP_ANDROID_TEST }}
  APP_NAME: ${{ ‘MyApp-Android/ENV_TEST’ }}
  TESTING_GROUP: ${{ ‘ENV_TEST’ }}
  UPLOAD_FILE: ${{ ‘android/app/build/outputs/apk/app-release.apk' }}
  
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+([0-9]+)'
  
jobs:
        build:
          name: Build
          runs-on: ubuntu-latest

          steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: set up JDK 1.8
              uses: actions/setup-java@v1
              with:
                java-version: 1.8   
