name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: node:14.16
      env:
        NODE_ENV: development
      ports:
        - 80
      volumes:
        - my_docker_volume:/volume_mount
      options: --cpus 1
    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
        
  container-test-job1:
      runs-on: ubuntu-latest 
      container:
        image: ghcr.io/owner/image
        credentials:
           username: ${{ github.actor }}
           password: ${{ secrets.github_token }}             
        volumes:
          - my_docker_volume:/volume_mount
          - /data/my_data
          - /source/directory:/destination/directory
