name: CI-CD-Pipeline-to_AWS
env:
  EB_PACKAGE_S3_BUCKET_NAME: "adv-it-flask-application-package"
  EB_APPLICATION_NAME: "MyFlask"
  EB_ENVIROMENT_NAME: "My-flask-env"
  DEPLOY_PACKAGE_NAME: "flask_app_${{ github.sha }}.zip"
  AWS_REGION_NAME: "us-west-2"

on:
 push:
   branches:
          - master


jobs:
  ci-pipline:
    runs-on: ubuntu-latest
    
    steps:
     - name: Run a one line script
     - uses: actions/checkout@v1
     - name: Create zip deployment package 
     - run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
     
     
    
